name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
        mongodb:
          image: mongo:latest
          ports:
            - 27017:27017

    strategy:
      matrix:
        node-version: [20.x]

    steps:

    - name: Checkout another repository
      uses: actions/checkout@v3
      with:
        repository: raphagoo/trivia-app-server
        ref: launch_api_from_front

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Set up test database
      run: |
        echo "MONGO_TEST_URL=mongodb://localhost:27017/trivia-app-test" >> .env
        echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env
        echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env
        echo "NODE_ENV=test" >> .env
        npm run fixtures

    - name: Start Api
      run: |
        nohup npm start &

    - name: Checkout current repository
      uses: actions/checkout@v3

    - name: Build
      run: |
        npm install --force
    - name: Prettier
      run: |
        npm run prettier-check
    - name: Lint
      run: |
        npm run lint
    - name: Test
      run: |
        npm run test
    - name: Run
      run: |
        npm run build

