name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:

    - name: Checkout another repository
      uses: actions/checkout@v3
      with:
        repository: raphagoo/trivia-app-server

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build API
      run: |
        npm install --force
        npm run build  # replace with your build command


    - name: Checkout current repository
      uses: actions/checkout@v3

    - name: Build
      run: |
        npm install --force
    - name: Prettier
      run: |
        npm run prettier-check
    - name: Lint
      run: |
        npm run lint
    - name: Test
      run: |
        npm run test
    - name: Run
      run: |
        npm run build

